-- !Ups
CREATE TABLE "USERS" (
	"ID" UUID PRIMARY KEY,
	"USERNAME" VARCHAR(255) NOT NULL,
	"PASSWORD" VARCHAR(255) NOT NULL
);

CREATE TABLE "CONTACT" (
	"ID" UUID PRIMARY KEY,
	"USER_ID" UUID REFERENCES "USERS" ("ID"),
	"FIRST_NAME" VARCHAR(255),
	"MIDDLE_NAME" VARCHAR(255),
	"LAST_NAME" VARCHAR(255),
	"PHONE_NUMBER" VARCHAR(255),
	"EMAIL" VARCHAR(255)
);

-- !Downs
DROP TABLE IF EXISTS "USERS";
DROP TABLE IF EXISTS "CONTACT";