-- !Ups

CREATE TABLE "STAR" (
	"ID" UUID PRIMARY KEY,
	"KEYWORD" VARCHAR(255)
);

CREATE TABLE "COLLECTION" (
	"ID" UUID PRIMARY KEY,
	"STAR_ID" UUID REFERENCES "STAR" ("ID"),
	"NAME" VARCHAR(255) NOT NULL
);

-- !Downs

DROP TABLE IF EXISTS "STAR";
DROP TABLE IF EXISTS "COLLECTION";