-- !Ups
CREATE TABLE "TODO_LIST" (
    "ID" UUID PRIMARY KEY,
    "USER_ID" UUID REFERENCES "USERS" ("ID"),
    "TASK" VARCHAR(255) NOT NULL,
    "COMPLETED" BOOLEAN NOT NULL
);

-- !Downs
DROP TABLE IF EXISTS "TODO_LIST";